### ISSUE TITLE
Missing dependency `blinker` for `bugsnag[flask]`

### ISSUE THREAD

**Issue by evandam** [bugsnag/bugsnag-python#184]
This error is thrown when running `handle_exceptions(app)` to register Bugsnag with Flask.

`pip install blinker` resolves the issue, but it should be properly listed as a dependency of the bugsnag package.

```
[2019-08-28 19:00:22 +0000] [8] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/usr/src/app/wsgi.py", line 8, in 
    application = create_app()
  File "/usr/src/app/app.py", line 196, in create_app
    handle_exceptions(app)
  File "/usr/local/lib/python3.7/site-packages/bugsnag/flask/__init__.py", line 33, in handle_exceptions
    flask.got_request_exception.connect(__log_exception, app)
  File "/usr/local/lib/python3.7/site-packages/flask/signals.py", line 39, in _fail
    "Signalling support is unavailable because the blinker"
RuntimeError: Signalling support is unavailable because the blinker library is not installed.
```

**Comment by tomlongridge** [comment]
@evandam, `blinker` is listed as a dependency of the extra `flask` integration. Therefore you should get it installed if you run `pip install bugsnag[flask]`:
```
Collecting bugsnag[flask]
  [...]
Collecting webob (from bugsnag[flask])
  [...]
Collecting six<2,>=1.9 (from bugsnag[flask])
  [...]
Collecting blinker; extra == "flask" (from bugsnag[flask])
  [...]
Collecting flask; extra == "flask" (from bugsnag[flask])
  [...]
Collecting Jinja2>=2.10.1 (from flask; extra == "flask"->bugsnag[flask])
  [...]
Collecting itsdangerous>=0.24 (from flask; extra == "flask"->bugsnag[flask])
  [...]
Collecting click>=5.1 (from flask; extra == "flask"->bugsnag[flask])
  [...]
Collecting Werkzeug>=0.15 (from flask; extra == "flask"->bugsnag[flask])
  [...]
Collecting MarkupSafe>=0.23 (from Jinja2>=2.10.1->flask; extra == "flask"->bugsnag[flask])
  [...]
Installing collected packages: webob, six, blinker, MarkupSafe, Jinja2, itsdangerous, click, Werkzeug, flask, bugsnag
Successfully installed Jinja2-2.10.1 MarkupSafe-1.1.1 Werkzeug-0.15.5 blinker-1.4 bugsnag-3.6.0 click-7.0 flask-1.1.1 itsdangerous-1.1.0 six-1.12.0 webob-1.8.5
```
Can you check your output and let us know if you see any differently?

**Comment by evandam** [comment]
:+1: I think I must've run a previous version where I only installed `blinker`, not `blinker[flask]`. Sorry about that!
